version: '1.0'
services:
  - name: db
    type: mariadb
    version: 10.3
    configuration: MasterSlave
    username: wordpress
    # Ask password on create
    userPassword: null
    password: null
    ports:
      - 3306
    remoteAccess: false
    comments:
      username: Database will be created with the same name
    deployTo:
      - mainOne
      - mainTwo

  - name: cache
    type: redis
    version: 4.0
    remoteAccess: false
    ports:
      - 6379
    deployTo:
      - edge

  - name: blog
    type: php
    version: 7.1
    source:
      type: download
      url: https://wordpress.org/latest.zip
    extensions:
      - mysqli
      - opcache
      - gd
      - zip
      - soap
    pecl:
      - redis
    volumes:
      - directory: $MAIN_PATH/wp-content/uploads
        sync: true
      - directory: $MAIN_PATH/wp-content/plugins
        sync: true
      - directory: $MAIN_PATH/wp-content/themes
        sync: true
    configFiles:
      - dest: $MAIN_PATH/wp-config.php
        src: ./configs/wp-config.php
      - dest: $MAIN_PATH/db-config.php
        src: ./configs/db-config.php
      - dest: $MAIN_PATH/wp-content/db.php
        src: ./configs/db.php
    globalDeps: |
      apt-get install less mysql-client
      curl https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -o /usr/local/bin/wp
      chmod +x /usr/local/bin/wp
      echo 'alias wp="wp --allow-root"' >> ~/.bashrc
      cp -r $MAIN_PATH/wp-content/themes ~/themes
    localDeps: cp -r ~/themes/* $MAIN_PATH/wp-content/themes/
    initialCommands: |
      cd $MAIN_PATH
      wp core install --url=$WP_URL --title="$WP_TITLE" --admin_user=$WP_ADMIN_USERNAME --admin_password=$WP_ADMIN_PASSWORD --admin_email=$WP_ADMIN_EMAIL
      wp plugin install varnish-http-purge --activate
      wp plugin install redis-cache --activate
      wp redis enable
    env:
      WP_URL: "{{=service('varnish').getNginxDomain()}}"
      WP_TITLE: null
      WP_ADMIN_USERNAME: null
      WP_ADMIN_PASSWORD: null
      WP_ADMIN_EMAIL: null
    comments:
      env:
        WP_TITLE: The title of your Wordpress website
        WP_ADMIN_USERNAME: Username of administrator account
        WP_ADMIN_PASSWORD: Password of administrator account
        WP_ADMIN_EMAIL: Email of administrator account
    deployTo:
      - mainOne
      - mainTwo

  - name: cluster
    type: nginxCluster
    version: 1.13
    ports:
      - 80
      - 443
    remoteAccess: false
    serviceFiles:
      - name: blog
        static: true
    deployTo:
      - mainOne
      - mainTwo

  - name: balancer
    type: haproxy
    version: latest
    ports:
      - 80
      - 443
    remoteAccess: false
    serviceFiles:
      - name: cluster
        sticky: true
    deployTo:
      - edge

  - name: varnish
    type: docker
    image: d2cio/varnish
    version: 6.0
    ports:
      - 80
    remoteAccess: false
    configFiles:
      - dest: /etc/varnish/default.vcl
        src: ./configs/default.vcl
    deployTo:
      - edge

  - name: pma
    type: php
    version: 7.1
    source:
      type: git
      url: https://github.com/phpmyadmin/phpmyadmin
      version: STABLE
    extensions:
      - mysqli
      - opcache
    configFiles:
      - dest: $MAIN_PATH/config.inc.php
        src: ./configs/config.inc.php
    localDeps: composer install
    deployTo:
      - edge

  - name: web
    type: nginx
    version: 1.13
    ports:
      - 80
      - 443
    remoteAccess: true
    serviceFiles:
      - name: pma
        static: true
      - name: varnish
    deployTo:
      - edge

hosts:
  - name: mainOne
    requirements:
      cores: 1
      memory: 2

  - name: mainTwo
    requirements:
      cores: 1
      memory: 2

  - name: edge
    requirements:
      cores: 1
      memory: 1
