version: "1.0"
services:
  - name: db
    type: mariadb
    version: 10.4
    configuration: MasterSlave
    database: wordpress
    username: wordpress
    # Ask password on create
    userPassword: null
    password: null
    ports:
      - 3306
    remoteAccess: false
    comments:
      username: Database will be created with the same name
    deployTo:
      - main-one
      - main-two

  - name: cache
    type: redis
    version: 5.0
    remoteAccess: false
    ports:
      - 6379
    deployTo:
      - edge

  - name: cache
    type: redis
    version: 5.0
    remoteAccess: false
    ports:
      - 6379
    deployTo:
      - edge

  - name: balancer
    type: haproxy
    version: latest
    ports:
      - 80
      - 443
    remoteAccess: false
    serviceFiles:
      - name: blog
        sticky: true
    deployTo:
      - edge

  - name: varnish
    type: docker
    image: d2cio/varnish
    version: 6.0
    ports:
      - 80
    remoteAccess: false
    configFiles:
      - dest: /etc/varnish/default.vcl
        src: ./configs/default.vcl
    deployTo:
      - edge

  - name: pma
    type: docker
    image: phpmyadmin/phpmyadmin
    version: latest
    ports:
      - 80
    remoteAccess: false
    env:
      PMA_HOST: "{{=service('db').getMasterAlias()}}"
      PMA_PORT: "{{=service('db').getMainPort()}}"
    deployTo:
      - edge

  - name: web
    type: nginx
    version: 1.17
    ports:
      - 80
      - 443
    remoteAccess: true
    serviceFiles:
      - name: varnish
      - name: pma
    deployTo:
      - edge

hosts:
  - name: main-one
    requirements:
      cores: 1
      memory: 2

  - name: main-two
    requirements:
      cores: 1
      memory: 2

  - name: edge
    requirements:
      cores: 1
      memory: 1
